<Project>
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>3.1.1</Version>
    <AssemblyVersion>3.1.1.0</AssemblyVersion>
    <FileVersion>3.1.1.0</FileVersion>
    <InformationalVersion>3.1.1</InformationalVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <Product>AudioSwitch</Product>
    <Authors>Tanel Teede</Authors>
    <Copyright>Copyright (c) Tanel Teede 2026</Copyright>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <DebugType>none</DebugType>
  </PropertyGroup>
</Project>
